[2024-10-13T11:02:23.514+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T11:02:23.522+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-10-13T11:02:15.292187+00:00 [queued]>
[2024-10-13T11:02:23.525+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-10-13T11:02:15.292187+00:00 [queued]>
[2024-10-13T11:02:23.525+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-13T11:02:23.530+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): train_model> on 2024-10-13 11:02:15.292187+00:00
[2024-10-13T11:02:23.532+0000] {standard_task_runner.py:72} INFO - Started process 59915 to run task
[2024-10-13T11:02:23.533+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2024-10-13T11:02:15.292187+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpgv7abk5_']
[2024-10-13T11:02:23.533+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask train_model
[2024-10-13T11:02:23.560+0000] {task_command.py:467} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2024-10-13T11:02:15.292187+00:00 [running]> on host haserver
[2024-10-13T11:02:23.593+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T11:02:15.292187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T11:02:15.292187+00:00'
[2024-10-13T11:02:23.593+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T11:02:23.599+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-13T11:02:23.599+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/dblab/haeun/mlops/ml_***/ex1/scripts/train_model.py']
[2024-10-13T11:02:23.602+0000] {subprocess.py:86} INFO - Output:
[2024-10-13T11:02:24.122+0000] {subprocess.py:93} INFO - 2024/10/13 11:02:24 INFO mlflow.tracking.fluent: Experiment with name 'train_model' does not exist. Creating a new experiment.
[2024-10-13T11:02:24.126+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-13T11:02:24.126+0000] {subprocess.py:93} INFO -   File "/home/dblab/haeun/mlops/ml_***/ex1/scripts/train_model.py", line 15, in <module>
[2024-10-13T11:02:24.126+0000] {subprocess.py:93} INFO -     df = pd.read_csv(f'{PROJECT_PATH}/datasets/data_train.csv', header=None)
[2024-10-13T11:02:24.126+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-13T11:02:24.126+0000] {subprocess.py:93} INFO -   File "/home/dblab/haeun/mlops/ml_***/ex1/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
[2024-10-13T11:02:24.126+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2024-10-13T11:02:24.126+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -   File "/home/dblab/haeun/mlops/ml_***/ex1/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -   File "/home/dblab/haeun/mlops/ml_***/ex1/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -   File "/home/dblab/haeun/mlops/ml_***/ex1/venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -     return mapping[engine](f, **self.options)
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -   File "/home/dblab/haeun/mlops/ml_***/ex1/venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -     self._reader = parsers.TextReader(src, **kwds)
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO -   File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
[2024-10-13T11:02:24.127+0000] {subprocess.py:93} INFO - pandas.errors.EmptyDataError: No columns to parse from file
[2024-10-13T11:02:24.209+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-13T11:02:24.217+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-13T11:02:24.220+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=train_model, run_id=manual__2024-10-13T11:02:15.292187+00:00, execution_date=20241013T110215, start_date=20241013T110223, end_date=20241013T110224
[2024-10-13T11:02:24.228+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T11:02:24.229+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 59915)
Traceback (most recent call last):
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-13T11:02:24.266+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T11:02:24.305+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T11:02:24.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
